#数据库相关信息
spring:
  datasource:
    username: root
    password: mysqlycsys
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.156.9:33060/jobduplicationcheck

mybatis:
  #  mybatis mapper映射文件路径
  mapper-locations: classpath*:mapper/*.xml
  #  打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl